### ISSUE TITLE
Use secure cookies

### ISSUE THREAD

**Issue by jace** [hasgeek/hasgeek.tv#228]
HGTV needs to have `SESSION_COOKIE_SECURE = True` in production settings since the app is only available via HTTPS.

**Comment by iambibhas** [comment]
I've set it in production settings. Now the cookies are set as secure. 

<img width="461" alt="HasGeek_TV_—_HasGeek_TV" src="https://user-images.githubusercontent.com/357253/58015823-d9ccfe80-7b19-11e9-804e-616d0e6297e9.png">
